### ISSUE TITLE
Issue when using gerrit-check on ubuntu

### ISSUE THREAD

**Issue by SiElHocine** [grundprinzip/gerrit-check#10]
I have this error when running the gerrit-check  command:
`Traceback (most recent call last):
  File "/usr/local/bin/gerrit-check", line 9, in <module>
    load_entry_point('gerrit-check==0.1.1', 'console_scripts', 'gerrit-check')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/gerritcheck/check.py", line 18, in <module>
    from flake8.engine import  get_style_guide
ImportError: No module named engine`

I installed gerrit-check using pip.

Python version 2.7.6
Ubuntu 14.04.5 LTS

I have the same error when installing it on windows.

**Comment by SiElHocine** [comment]
This pull request is fixing reported issue:
https://github.com/grundprinzip/gerrit-check/pull/9

**Comment by SiElHocine** [comment]
closed since #9  has been merged to master
